name = "Astrals-SMP-Full"
author = "Lunyxed (Maintainer - TDoggi)"
version = "2.0.0a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ec521347851faf6f2151bba10d9a59de45467945235d42467f00c2646217565e"

[versions]
fabric = "0.16.0"
minecraft = "1.20.1"
